# Generated by Django 5.0.1 on 2024-01-21 10:46

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/default_user.svg', upload_to=users.models.upload_to),
        ),
    ]
